#!/bin/bash



head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet15_Official_forests.txt >>    test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet30_Official_forests.txt >>    test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet50_Official_forests.txt >>    test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet80_Official_forests.txt >>    test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet120_Official_forests.txt >>   test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet170_Official_forests.txt >>   test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet220_Official_forests.txt >>   test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet280_Official_forests.txt >>   test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt
head -5 5p02TeV_Py8_CUETP8M1_QCDjet_Official_forests_individualBins/5p02TeV_Py8_CUETP8M1_QCDjet370_Official_forests.txt >>   test_readForests_ppMC_Py8_CUETP8M1_Official_forests_acrossBins.txt