#include <cstdlib>
#include <cstring>
#include <iostream>

#include "TROOT.h"
#include "TFile.h"
//#include "TIter.h"
#include "TKey.h"
#include "TClass.h"
#include "TH1.h"

//void loopdir() {

void testIter() {
  
  // example of script to loop on all the objects of a ROOT file directory
  // and print on Postscript all TH1 derived objects
  // This script uses the file generated by tutorial hsimple.C
  //Author: Rene Brun

  TFile *f1 = TFile::Open("fnl5020_LO2_R04Jets_modify_NNPDF30_nnlo_as_0121_MC_gaussSmear_00eta20.root");
  TIter next(f1->GetListOfKeys());

  TKey *key;
  //TCanvas c1;
  //c1.Print("hsimple.ps[");
  while ((key = (TKey*)next())) {
    TClass *cl = gROOT->GetClass(key->GetClassName());
    if (!cl->InheritsFrom("TH1")) continue;
    TH1 *h = (TH1*)key->ReadObj();
    std::cout<<"found TH1 histogram! h->GetName()="<<h->GetName()<<std::endl;
    
    //h->Draw();
    //c1.Print("hsimple.ps");
  }
  //c1.Print("hsimple.ps]");
  return;
}

