#!/bin/bash

xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_1.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_10.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_100.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_101.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_102.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_103.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_104.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_105.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_106.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_107.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_108.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_109.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_11.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_110.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_111.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_112.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_113.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_114.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_115.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_116.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_117.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_118.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_119.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_12.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_120.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_121.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_122.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_123.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_124.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_125.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_126.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_127.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_128.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_129.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_13.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_130.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_131.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_132.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_133.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_134.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_135.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_136.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_137.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_138.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_139.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_14.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_140.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_141.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_142.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_143.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_144.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_145.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_146.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_147.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_148.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_149.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_15.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_150.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_151.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_152.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_153.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_154.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_155.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_156.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_157.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_158.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_159.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_16.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_160.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_161.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_162.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_163.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_164.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_165.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_166.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_167.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_168.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_169.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_17.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_170.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_171.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_172.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_173.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_174.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_175.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_176.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_177.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_178.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_179.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_180.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_181.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_182.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_183.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_184.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_185.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_186.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_187.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_188.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_189.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_19.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_190.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_191.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_192.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_193.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_194.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_195.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_196.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_197.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_198.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_199.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_2.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_20.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_200.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_201.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_202.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_203.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_204.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_205.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_206.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_207.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_208.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_209.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_21.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_210.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_211.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_212.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_213.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_214.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_215.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_216.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_217.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_218.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_219.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_22.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_220.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_221.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_222.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_223.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_224.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_225.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_226.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_227.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_228.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_229.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_23.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_230.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_231.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_232.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_233.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_234.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_235.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_236.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_237.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_238.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_239.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_24.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_240.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_241.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_242.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_243.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_244.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_245.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_246.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_247.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_248.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_249.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_25.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_250.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_251.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_252.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_253.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_254.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_255.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_256.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_257.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_258.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_259.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_26.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_260.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_261.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_262.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_263.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_264.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_265.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_266.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_267.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_268.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_269.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_27.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_270.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_271.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_272.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_273.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_274.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_275.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_276.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_277.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_278.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_279.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_28.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_280.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_281.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_282.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_283.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_284.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_285.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_286.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_287.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_288.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_289.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_29.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_290.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_291.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_292.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_293.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_294.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_295.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_296.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_297.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_298.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_299.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_3.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_30.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_300.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_301.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_302.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_303.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_304.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_305.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_306.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_307.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_308.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_309.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_31.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_310.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_311.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_312.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_313.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_314.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_315.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_316.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_317.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_318.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_319.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_32.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_320.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_321.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_322.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_323.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_324.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_325.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_326.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_327.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_328.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_329.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_33.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_330.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_331.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_332.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_333.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_334.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_335.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_336.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_337.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_338.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_339.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_34.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_340.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_341.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_342.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_343.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_344.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_345.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_346.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_347.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_348.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_349.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_35.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_350.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_351.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_352.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_353.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_354.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_355.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_356.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_357.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_358.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_359.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_360.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_361.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_362.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_363.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_364.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_365.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_366.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_367.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_368.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_369.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_37.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_370.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_371.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_372.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_373.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_374.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_375.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_376.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_379.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_38.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_380.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_381.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_382.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_383.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_384.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_385.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_386.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_387.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_388.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_389.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_39.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_390.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_391.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_392.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_393.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_394.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_395.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_396.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_397.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_398.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_399.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_4.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_40.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_400.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_401.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_402.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_403.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_404.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_405.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_406.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_407.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_408.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_409.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_41.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_410.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_411.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_412.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_413.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_414.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_415.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_416.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_417.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_418.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_419.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_42.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_420.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_421.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_422.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_423.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_424.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_425.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_426.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_427.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_428.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_429.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_43.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_430.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_431.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_432.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_433.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_434.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_435.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_436.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_437.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_438.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_439.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_44.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_440.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_441.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_45.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_46.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_47.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_48.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_49.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_5.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_50.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_51.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_52.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_53.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_54.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_55.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_56.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_57.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_58.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_59.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_6.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_60.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_61.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_62.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_63.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_64.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_65.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_66.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_67.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_68.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_69.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_7.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_70.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_71.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_72.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_73.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_74.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_75.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_76.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_77.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_78.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_79.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_8.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_80.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_81.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_82.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_83.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_84.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_85.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_86.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_87.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_88.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_89.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_9.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_90.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_91.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_92.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_93.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_94.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_95.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_96.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_97.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_98.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtLowerJets/HiForestAOD_99.root    /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtLowerJets
