#!/bin/bash
#xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_1.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_10.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_100.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_101.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_102.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_103.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_104.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_105.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_106.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_107.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_108.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_109.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_11.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_110.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_111.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_112.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_113.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_114.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_115.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_116.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_117.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_118.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_119.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_12.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_120.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_121.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_122.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_123.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_124.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_125.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_126.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_127.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_128.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_129.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_13.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_130.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_131.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_132.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_133.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_134.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_135.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_136.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_137.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_138.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_139.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_14.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_140.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_141.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_142.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_143.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_144.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_145.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_146.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_147.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_148.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_149.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_15.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_150.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_151.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_152.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_153.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_154.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_155.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_156.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_157.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_158.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_159.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_16.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_160.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_161.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_162.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_163.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_164.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_165.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_166.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_167.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_168.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_169.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_17.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_170.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_171.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_172.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_173.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_174.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_175.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_176.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_177.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_178.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_179.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_18.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_180.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_181.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_182.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_183.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_184.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_185.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_186.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_187.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_188.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_189.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_19.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_190.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_191.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_192.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_193.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_194.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_195.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_196.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_197.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_198.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_199.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_2.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_20.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_200.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_201.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_202.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_203.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_204.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_205.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_206.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_207.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_208.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_209.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_21.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_210.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_211.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_212.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_213.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_214.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_215.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_216.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_217.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_218.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_219.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_22.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_220.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_221.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_222.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_223.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_224.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_225.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_226.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_227.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_228.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_229.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_23.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_230.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_231.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_232.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_233.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_234.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_235.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_236.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_237.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_238.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_239.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_24.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_240.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_241.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_242.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_243.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_244.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_245.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_246.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_247.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_248.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_249.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_25.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_250.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_251.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_252.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_253.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_254.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_255.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_256.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_257.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_258.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_259.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_26.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_260.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_261.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_262.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_263.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_264.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_265.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_266.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_267.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_268.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_269.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_27.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_270.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_271.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_272.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_273.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_274.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_275.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_276.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_277.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_278.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_279.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_28.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_280.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_281.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_282.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_283.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_284.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_285.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_286.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_287.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_288.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_289.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_29.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_290.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_291.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_292.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_293.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_294.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_295.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_296.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_297.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_298.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_299.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_3.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_30.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_300.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_301.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_302.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_303.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_304.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_305.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_306.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_307.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_308.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_309.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_31.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_310.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_311.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_312.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_313.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_314.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_315.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_316.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_317.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_318.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_319.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_32.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_320.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_321.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_322.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_323.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_324.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_325.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_326.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_327.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_328.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_329.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_33.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_330.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_331.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_332.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_333.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_334.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_335.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_336.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_337.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_338.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_339.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_34.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_340.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_341.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_342.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_343.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_344.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_345.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_346.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_347.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_348.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_349.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_35.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_350.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_351.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_352.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_353.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_354.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_355.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_356.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_357.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_358.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_359.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_36.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_360.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_361.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_362.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_363.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_364.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_365.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_366.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_367.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_368.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_369.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_37.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_370.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_371.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_372.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_373.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_374.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_375.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_376.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_377.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_378.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_379.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_38.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_380.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_381.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_382.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_383.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_384.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_385.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_386.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_387.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_388.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_389.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_39.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_390.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_391.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_392.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_393.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_394.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_4.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_40.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_41.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_42.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_43.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_44.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_45.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_46.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_47.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_48.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_49.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_5.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_50.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_51.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_52.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_53.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_54.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_55.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_56.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_57.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_58.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_59.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_6.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_60.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_61.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_62.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_63.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_64.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_65.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_66.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_67.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_68.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_69.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_7.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_70.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_71.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_72.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_73.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_74.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_75.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_76.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_77.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_78.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_79.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_8.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_80.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_81.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_82.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_83.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_84.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_85.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_86.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_87.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_88.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_89.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_9.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_90.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_91.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_92.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_93.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_94.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_95.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_96.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_97.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_98.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
xrdcp root://cmsxrootd.fnal.gov//store/user/abaty/transferTargetDirectories/2015pp_HighPtJet80/HiForestAOD_99.root     /cms/se/store/user/ilaflott/jobOutput2/2015pp_HighPtJet80
